/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as FonTestRouteImport } from './routes/fon-test'
import { Route as JamoaRouteImport } from './routes/jamoa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MahsulotlarRouteImport } from './routes/mahsulotlar'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as OperatorlarRouteImport } from './routes/operatorlar'
import { Route as ReytingIshchiRouteImport } from './routes/reyting.ishchi'
import { Route as ReytingMenejerRouteImport } from './routes/reyting.menejer'
import { Route as ReytingSupervayzerRouteImport } from './routes/reyting.supervayzer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const FonTestRoute = FonTestRouteImport.update({
  id: '/fon-test',
  path: '/fon-test',
  getParentRoute: () => rootRouteImport,
} as any)
const JamoaRoute = JamoaRouteImport.update({
  id: '/jamoa',
  path: '/jamoa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MahsulotlarRoute = MahsulotlarRouteImport.update({
  id: '/mahsulotlar',
  path: '/mahsulotlar',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorlarRoute = OperatorlarRouteImport.update({
  id: '/operatorlar',
  path: '/operatorlar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReytingIshchiRoute = ReytingIshchiRouteImport.update({
  id: '/reyting/ishchi',
  path: '/reyting/ishchi',
  getParentRoute: () => rootRouteImport,
} as any)
const ReytingMenejerRoute = ReytingMenejerRouteImport.update({
  id: '/reyting/menejer',
  path: '/reyting/menejer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReytingSupervayzerRoute = ReytingSupervayzerRouteImport.update({
  id: '/reyting/supervayzer',
  path: '/reyting/supervayzer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/fon-test': typeof FonTestRoute
  '/jamoa': typeof JamoaRoute
  '/login': typeof LoginRoute
  '/mahsulotlar': typeof MahsulotlarRoute
  '/operator': typeof OperatorRoute
  '/operatorlar': typeof OperatorlarRoute
  '/reyting/ishchi': typeof ReytingIshchiRoute
  '/reyting/menejer': typeof ReytingMenejerRoute
  '/reyting/supervayzer': typeof ReytingSupervayzerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/fon-test': typeof FonTestRoute
  '/jamoa': typeof JamoaRoute
  '/login': typeof LoginRoute
  '/mahsulotlar': typeof MahsulotlarRoute
  '/operator': typeof OperatorRoute
  '/operatorlar': typeof OperatorlarRoute
  '/reyting/ishchi': typeof ReytingIshchiRoute
  '/reyting/menejer': typeof ReytingMenejerRoute
  '/reyting/supervayzer': typeof ReytingSupervayzerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/fon-test': typeof FonTestRoute
  '/jamoa': typeof JamoaRoute
  '/login': typeof LoginRoute
  '/mahsulotlar': typeof MahsulotlarRoute
  '/operator': typeof OperatorRoute
  '/operatorlar': typeof OperatorlarRoute
  '/reyting/ishchi': typeof ReytingIshchiRoute
  '/reyting/menejer': typeof ReytingMenejerRoute
  '/reyting/supervayzer': typeof ReytingSupervayzerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/fon-test'
    | '/jamoa'
    | '/login'
    | '/mahsulotlar'
    | '/operator'
    | '/operatorlar'
    | '/reyting/ishchi'
    | '/reyting/menejer'
    | '/reyting/supervayzer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/fon-test'
    | '/jamoa'
    | '/login'
    | '/mahsulotlar'
    | '/operator'
    | '/operatorlar'
    | '/reyting/ishchi'
    | '/reyting/menejer'
    | '/reyting/supervayzer'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/fon-test'
    | '/jamoa'
    | '/login'
    | '/mahsulotlar'
    | '/operator'
    | '/operatorlar'
    | '/reyting/ishchi'
    | '/reyting/menejer'
    | '/reyting/supervayzer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  FonTestRoute: typeof FonTestRoute
  JamoaRoute: typeof JamoaRoute
  LoginRoute: typeof LoginRoute
  MahsulotlarRoute: typeof MahsulotlarRoute
  OperatorRoute: typeof OperatorRoute
  OperatorlarRoute: typeof OperatorlarRoute
  ReytingIshchiRoute: typeof ReytingIshchiRoute
  ReytingMenejerRoute: typeof ReytingMenejerRoute
  ReytingSupervayzerRoute: typeof ReytingSupervayzerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fon-test': {
      id: '/fon-test'
      path: '/fon-test'
      fullPath: '/fon-test'
      preLoaderRoute: typeof FonTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jamoa': {
      id: '/jamoa'
      path: '/jamoa'
      fullPath: '/jamoa'
      preLoaderRoute: typeof JamoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mahsulotlar': {
      id: '/mahsulotlar'
      path: '/mahsulotlar'
      fullPath: '/mahsulotlar'
      preLoaderRoute: typeof MahsulotlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operatorlar': {
      id: '/operatorlar'
      path: '/operatorlar'
      fullPath: '/operatorlar'
      preLoaderRoute: typeof OperatorlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reyting/ishchi': {
      id: '/reyting/ishchi'
      path: '/reyting/ishchi'
      fullPath: '/reyting/ishchi'
      preLoaderRoute: typeof ReytingIshchiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reyting/menejer': {
      id: '/reyting/menejer'
      path: '/reyting/menejer'
      fullPath: '/reyting/menejer'
      preLoaderRoute: typeof ReytingMenejerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reyting/supervayzer': {
      id: '/reyting/supervayzer'
      path: '/reyting/supervayzer'
      fullPath: '/reyting/supervayzer'
      preLoaderRoute: typeof ReytingSupervayzerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  FonTestRoute: FonTestRoute,
  JamoaRoute: JamoaRoute,
  LoginRoute: LoginRoute,
  MahsulotlarRoute: MahsulotlarRoute,
  OperatorRoute: OperatorRoute,
  OperatorlarRoute: OperatorlarRoute,
  ReytingIshchiRoute: ReytingIshchiRoute,
  ReytingMenejerRoute: ReytingMenejerRoute,
  ReytingSupervayzerRoute: ReytingSupervayzerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
